services:
  - type: web
    name: moonsec-medal-bot
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: PORT
        value: 3000
    healthCheckPath: /
